require(ggplot2)
require(reshape2)
d<-read.csv('data/parameter.log.info1',sep=' ',header=T)
mean(d$Speciation_rate)
quantile(d$Speciation_rate,c(0.05,0.95))
mean(d$Extinction_rate)
quantile(d$Extinction_rate,c(0.05,0.95))
mean(d$Generations)
quantile(d$Generations,c(0.05,0.95))
q<-read.csv('data/quartetScores.csv', sep=' ',header=T)
mean(q$TrueQscore)
quantile(q$TrueQscore,c(0.05,0.95))
